const { Octokit } = require("@octokit/rest");
const { buildPrompt } = require("./reviewPrompt");
const { MODEL, runPrompt } = require("./claude");
const { MARKER, fetchPrContext, findStickyComment } = require("./prContext");

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

const [owner, repo] = process.env.REPO.split("/");
const prNumber = parseInt(process.env.PR_NUMBER, 10);

async function main() {
  // Step 1: PR metadata, changed files, file inventory, and capped diff text
  const { pr, files, fileTable, diffSummary } = await fetchPrContext(octokit, owner, repo, prNumber);

  if (files.length === 0) {
    console.log("No files changed in this PR. Skipping review.");
    return;
  }

  // Step 2: Ask Claude for a summary, a review, a verdict, and a fix prompt
  const prompt = buildPrompt({
    prNumber,
    title: pr.title,
    author: pr.user?.login,
    body: pr.body,
    fileTable,
    diffSummary,
  });

  const { text: reviewContent } = await runPrompt(prompt, process.env.ANTHROPIC_API_KEY);

  if (!reviewContent) {
    throw new Error("Claude returned no text content for the review.");
  }

  const body = `${MARKER}
# 🤖 Automated PR Review — #${prNumber}

> Generated by the PR Review Agent (Anthropic Claude \`${MODEL}\`).
> Reviewing ${files.length} changed file(s). This comment updates automatically on each push.

${reviewContent}`;

  // Step 3: Create or update a single sticky comment on the PR
  const existing = await findStickyComment(octokit, owner, repo, prNumber);

  if (existing) {
    await octokit.issues.updateComment({
      owner,
      repo,
      comment_id: existing.id,
      body,
    });
    console.log(`✅ Updated review comment on PR #${prNumber}`);
  } else {
    await octokit.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body,
    });
    console.log(`✅ Posted review comment on PR #${prNumber}`);
  }
}

main().catch((e) => {
  console.error("❌ Review agent failed:", e.message);
  process.exit(1);
});
