const { Octokit } = require("@octokit/rest");
const { buildPrompt } = require("./reviewPrompt");
const { MODEL, runReview } = require("./gemini");

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

const [owner, repo] = process.env.REPO.split("/");
const prNumber = parseInt(process.env.PR_NUMBER, 10);

// Hidden marker so we can find & update our own comment instead of posting a new
// one on every push (keeps a single, always-current review comment per PR).
const MARKER = "<!-- gemini-pr-review-agent -->";

// Keep the prompt within a sane token budget: cap each file's patch and the total.
const MAX_PATCH_CHARS = 12000;
const MAX_TOTAL_DIFF_CHARS = 90000;

async function main() {
  // Step 1: PR metadata + changed files
  const { data: pr } = await octokit.pulls.get({
    owner,
    repo,
    pull_number: prNumber,
  });

  const { data: files } = await octokit.pulls.listFiles({
    owner,
    repo,
    pull_number: prNumber,
    per_page: 100,
  });

  if (files.length === 0) {
    console.log("No files changed in this PR. Skipping review.");
    return;
  }

  // Step 2: A quick file inventory (always shown, even if a patch is truncated)
  const fileTable = files
    .map((f) => `- \`${f.filename}\` — ${f.status} (+${f.additions} / -${f.deletions})`)
    .join("\n");

  // Step 3: A readable diff for the model, with per-file and total size caps
  let total = 0;
  const diffParts = [];
  for (const f of files) {
    let patch = f.patch || "(no textual diff available — binary, renamed, or too large)";
    if (patch.length > MAX_PATCH_CHARS) {
      patch = patch.slice(0, MAX_PATCH_CHARS) + "\n... (patch truncated) ...";
    }
    const block = `File: ${f.filename}\nStatus: ${f.status} (+${f.additions} / -${f.deletions})\n\n${patch}`;
    if (total + block.length > MAX_TOTAL_DIFF_CHARS) {
      diffParts.push("... (remaining files omitted from diff due to size limits) ...");
      break;
    }
    diffParts.push(block);
    total += block.length;
  }
  const diffSummary = diffParts.join("\n\n---\n\n");

  // Step 4: Ask Gemini for a summary, a review, a verdict, and a fix prompt
  const prompt = buildPrompt({
    prNumber,
    title: pr.title,
    author: pr.user?.login,
    body: pr.body,
    fileTable,
    diffSummary,
  });

  const { text: reviewContent } = await runReview(prompt, process.env.GEMINI_API_KEY);

  if (!reviewContent) {
    throw new Error("Gemini returned no text content for the review.");
  }

  const body = `${MARKER}
# 🤖 Automated PR Review — #${prNumber}

> Generated by the PR Review Agent (Google Gemini \`${MODEL}\`).
> Reviewing ${files.length} changed file(s). This comment updates automatically on each push.

${reviewContent}`;

  // Step 5: Create or update a single sticky comment on the PR
  const { data: comments } = await octokit.issues.listComments({
    owner,
    repo,
    issue_number: prNumber,
    per_page: 100,
  });
  const existing = comments.find((c) => c.body && c.body.includes(MARKER));

  if (existing) {
    await octokit.issues.updateComment({
      owner,
      repo,
      comment_id: existing.id,
      body,
    });
    console.log(`✅ Updated review comment on PR #${prNumber}`);
  } else {
    await octokit.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body,
    });
    console.log(`✅ Posted review comment on PR #${prNumber}`);
  }
}

main().catch((e) => {
  console.error("❌ Review agent failed:", e.message);
  process.exit(1);
});
